import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="nextjs, adguin, smart contract nfts" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* <Script src="/sc.js" stratergy="lazyOnload"></Script>  */} 
      {/* scripts present in public directory */}

      <main id='grad0' className={styles.main}>
        <section className='w-[100vw] h-[100vh]'>
          <div className={styles.description}>
            <h1 className='h-32 font-abandoned text-center justify-center	text-9xl p-40 z-10 absolute not-italic font-thin text-black bg-none'>
                  THE BEST PRIVACY ONLINE
            </h1>
            <h3 className='pt-[60vh] pl-[500px] font-miriam text-center text-4xl justify-center p-48 z-10 absolute not-italic font-bold text-white bg-none'>
              Browse privately. Search privately. And ditch Big Tech.
            </h3>
          </div>

          <div className=' absolute bg-violet-700 z-10 ml-[500px] mt-[70vh] w-[109px] '>
                    <button class="font-miriam w-[150px]  hover:bg-violet-500 text-white font-light rounded">
                        SIGN UP
                    </button>
                </div>

          <div className="absolute z-10 mt-[80vh] ml-[10vw] w-[80vw] h-[20vh]">
              <div className={styles.box1}>This box uses opacity</div>
          </div>       

          <Image src={'/heroblur.png'} className="relative w-[100vw] z-0 top-0 h-[120vh] bg-white" width="1000" height="1000" />
        
               
              
        
        </section>
        
      </main> 
    </>
  )
}
